name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Write publish profile to directory
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: ${{ env.home }}/EtzMitzvotOnVm.pubxml
          contents: |
            ${{ secrets.ETZMITZVOT_PUBXML }}
          write-mode: overwrite

      - name: Setup MSbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Publish project
        run: |
          msbuild /p:DeployOnBuild=true /p:PublishProfile=${{ env.home }}/EtzMitzvotOnVm.pubxml /p:username=${{ secrets.IIS_USERNAME }} /p:password=${{ secrets.IIS_PASSWORD }}
